yarn run write-translations --locale ko 
yarn run write-translations --locale ln 
yarn run write-translations --locale lo 
yarn run write-translations --locale ml 
yarn run write-translations --locale my 
yarn run write-translations --locale ne 
yarn run write-translations --locale nl 
yarn run write-translations --locale om 
yarn run write-translations --locale or 
yarn run write-translations --locale ps 
yarn run write-translations --locale ro 
yarn run write-translations --locale ru 
yarn run write-translations --locale sw 
yarn run write-translations --locale ta 
yarn run write-translations --locale te 
yarn run write-translations --locale th 
yarn run write-translations --locale tl 
yarn run write-translations --locale tpi 
yarn run write-translations --locale tr 
yarn run write-translations --locale twi 
yarn run write-translations --locale uk 
yarn run write-translations --locale ur 
yarn run write-translations --locale vi 
yarn run write-translations --locale yo 
